# See https://openmod.github.io/openmod-docs/devdoc/concepts/configuration.html
# You can delete this file if you do not need a configuration

BLEEDING: "lost too much blood."
BONES: "got his ankles broken."
FREEZING: "froze to death."
BURNING: "was too hot to handle."
FOOD: "starved to death."
WATER: "dehydrated to death."
GUN: "was shot full of holes."
MELEE: "got shanked."
ZOMBIE: "was mauled to death."
ANIMAL: "died to bambie."
SUICIDE: "killed themselves."
KILL: "had a heart attack."
INFECTION: "got covid-19."
PUNCH: "was knocked out cold."
BREATH: "drowned."
ROADKILL: "was run over."
VEHICLE: "died to a vehicle."
GRENADE: "was blown up."
SHRED: "was thrown into a blender."
LANDMINE: "didnt watch his step."
ARENA: "didnt make it into the circle."
MISSILE: "was nuked."
CHARGE: "went boom."
SPLASH: "didnt get far enough away."
SENTRY: "wasnt sneaky enough."
ACID: "was melted."
BOULDER: "was crushed to death."
BURNER: "was burnt alive."
SPIT: "got spat on."
SPARK: "was electrocuted."
